begin;

alter table public.workspaces add constraint workspaces_profile_check check (profile_key in ('technology','cosmetics','fashion','food','custom'));
alter table public.workspaces add constraint workspaces_experience_check check (experience_mode in ('guided','compact'));
alter table public.workspace_members add constraint workspace_members_role_check check (role in ('owner','editor','viewer'));
alter table public.categories add constraint categories_workspace_code_unique unique (workspace_id, code);
alter table public.categories add constraint categories_id_workspace_unique unique (id, workspace_id);
alter table public.suppliers add constraint suppliers_id_workspace_unique unique (id, workspace_id);
alter table public.products add constraint products_id_workspace_unique unique (id, workspace_id);
alter table public.products add constraint products_workspace_nex_code_unique unique (workspace_id, nex_code);
alter table public.products add constraint products_tracking_check check (tracking_mode in ('bulk','batch','serialized'));
alter table public.products add constraint products_quantity_check check (current_quantity >= 0 and minimum_stock >= 0);
alter table public.products add constraint products_price_check check (purchase_price >= 0 and sale_price >= 0);
alter table public.products add constraint products_category_workspace_fk foreign key (category_id, workspace_id) references public.categories(id, workspace_id);
alter table public.products add constraint products_supplier_workspace_fk foreign key (supplier_id, workspace_id) references public.suppliers(id, workspace_id);
alter table public.product_units add constraint product_units_id_workspace_unique unique (id, workspace_id);
alter table public.product_units add constraint product_units_product_workspace_fk foreign key (product_id, workspace_id) references public.products(id, workspace_id);
alter table public.product_units add constraint product_units_workspace_serial_unique unique (workspace_id, serial_number);
alter table public.product_units add constraint product_units_condition_check check (condition in ('new','used','refurbished','damaged'));
alter table public.product_units add constraint product_units_lifecycle_check check (lifecycle_state in ('in_stock','assigned','maintenance','retired'));
alter table public.stock_batches add constraint stock_batches_product_number_unique unique (product_id, batch_number);
alter table public.stock_batches add constraint stock_batches_id_workspace_unique unique (id, workspace_id);
alter table public.stock_batches add constraint stock_batches_product_workspace_fk foreign key (product_id, workspace_id) references public.products(id, workspace_id);
alter table public.stock_batches add constraint stock_batches_quantity_check check (quantity >= 0);
alter table public.stock_movements add constraint stock_movements_type_check check (type in ('IN','OUT','ADJUSTMENT'));
alter table public.stock_movements add constraint stock_movements_quantity_check check (quantity > 0 and before_quantity >= 0 and after_quantity >= 0);
alter table public.stock_movements add constraint movements_product_workspace_fk foreign key (product_id, workspace_id) references public.products(id, workspace_id);
alter table public.stock_movements add constraint movements_unit_workspace_fk foreign key (product_unit_id, workspace_id) references public.product_units(id, workspace_id);
alter table public.stock_movements add constraint movements_batch_workspace_fk foreign key (batch_id, workspace_id) references public.stock_batches(id, workspace_id);
alter table public.product_relations add constraint product_relations_type_check check (relation_type in ('compatible_with','requires','replaces','upgrade_of','accessory_for'));
alter table public.product_relations add constraint product_relations_distinct_check check (source_product_id <> target_product_id);
alter table public.product_relations add constraint product_relations_unique unique (source_product_id, target_product_id, relation_type);
alter table public.product_relations add constraint relations_source_workspace_fk foreign key (source_product_id, workspace_id) references public.products(id, workspace_id);
alter table public.product_relations add constraint relations_target_workspace_fk foreign key (target_product_id, workspace_id) references public.products(id, workspace_id);
alter table public.kits add constraint kits_id_workspace_unique unique (id, workspace_id);
alter table public.kit_items add constraint kit_items_kit_workspace_fk foreign key (kit_id, workspace_id) references public.kits(id, workspace_id);
alter table public.kit_items add constraint kit_items_product_workspace_fk foreign key (product_id, workspace_id) references public.products(id, workspace_id);
alter table public.kit_items add constraint kit_items_product_unique unique (kit_id, product_id);
alter table public.kit_items add constraint kit_items_quantity_check check (quantity_required > 0);
alter table public.custom_field_definitions add constraint custom_fields_workspace_key_unique unique (workspace_id, key);
alter table public.custom_field_definitions add constraint custom_fields_type_check check (type in ('text','number','currency','date','boolean','select','multiselect','url'));
alter table public.sync_queue add constraint sync_queue_retry_check check (retry_count >= 0);
alter table public.sync_queue add constraint sync_queue_status_check check (status in ('pending','processing','completed','failed'));

commit;
