alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.meta enable row level security;
alter table public.categories enable row level security;
alter table public.suppliers enable row level security;
alter table public.products enable row level security;
alter table public.product_units enable row level security;
alter table public.stock_batches enable row level security;
alter table public.stock_movements enable row level security;
alter table public.audit_logs enable row level security;
alter table public.product_relations enable row level security;
alter table public.kits enable row level security;
alter table public.kit_items enable row level security;
alter table public.custom_field_definitions enable row level security;
alter table public.settings enable row level security;
alter table public.sync_queue enable row level security;

create policy workspaces_select on public.workspaces for select to authenticated using (public.is_workspace_member(id));
create policy workspaces_insert on public.workspaces for insert to authenticated with check (auth.uid() is not null);
create policy workspaces_update on public.workspaces for update to authenticated using (public.workspace_role(id) in ('owner','editor')) with check (public.workspace_role(id) in ('owner','editor'));
create policy workspaces_delete on public.workspaces for delete to authenticated using (public.workspace_role(id) = 'owner');

create policy members_select on public.workspace_members for select to authenticated using (user_id = auth.uid() or public.is_workspace_member(workspace_id));
create policy members_insert on public.workspace_members for insert to authenticated with check (public.workspace_role(workspace_id) = 'owner');
create policy members_update on public.workspace_members for update to authenticated using (public.workspace_role(workspace_id) = 'owner') with check (public.workspace_role(workspace_id) = 'owner');
create policy members_delete on public.workspace_members for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');

create policy meta_select on public.meta for select to authenticated using (user_id = auth.uid());
create policy meta_insert on public.meta for insert to authenticated with check (user_id = auth.uid());
create policy meta_update on public.meta for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy meta_delete on public.meta for delete to authenticated using (user_id = auth.uid());

create policy categories_select on public.categories for select to authenticated using (public.is_workspace_member(workspace_id));
create policy categories_insert on public.categories for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy categories_update on public.categories for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy categories_delete on public.categories for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy suppliers_select on public.suppliers for select to authenticated using (public.is_workspace_member(workspace_id));
create policy suppliers_insert on public.suppliers for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy suppliers_update on public.suppliers for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy suppliers_delete on public.suppliers for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy products_select on public.products for select to authenticated using (public.is_workspace_member(workspace_id));
create policy products_insert on public.products for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy products_update on public.products for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy products_delete on public.products for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy product_units_select on public.product_units for select to authenticated using (public.is_workspace_member(workspace_id));
create policy product_units_insert on public.product_units for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy product_units_update on public.product_units for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy product_units_delete on public.product_units for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy batches_select on public.stock_batches for select to authenticated using (public.is_workspace_member(workspace_id));
create policy batches_insert on public.stock_batches for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy batches_update on public.stock_batches for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy batches_delete on public.stock_batches for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy movements_select on public.stock_movements for select to authenticated using (public.is_workspace_member(workspace_id));
create policy movements_insert on public.stock_movements for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy audit_select on public.audit_logs for select to authenticated using (public.is_workspace_member(workspace_id));
create policy audit_insert on public.audit_logs for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy relations_select on public.product_relations for select to authenticated using (public.is_workspace_member(workspace_id));
create policy relations_insert on public.product_relations for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy relations_update on public.product_relations for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy relations_delete on public.product_relations for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy kits_select on public.kits for select to authenticated using (public.is_workspace_member(workspace_id));
create policy kits_insert on public.kits for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy kits_update on public.kits for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy kits_delete on public.kits for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy kit_items_select on public.kit_items for select to authenticated using (public.is_workspace_member(workspace_id));
create policy kit_items_insert on public.kit_items for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy kit_items_update on public.kit_items for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy kit_items_delete on public.kit_items for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy custom_fields_select on public.custom_field_definitions for select to authenticated using (public.is_workspace_member(workspace_id));
create policy custom_fields_insert on public.custom_field_definitions for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy custom_fields_update on public.custom_field_definitions for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy custom_fields_delete on public.custom_field_definitions for delete to authenticated using (public.workspace_role(workspace_id) = 'owner');
create policy settings_select on public.settings for select to authenticated using (user_id = auth.uid() and public.is_workspace_member(workspace_id));
create policy settings_insert on public.settings for insert to authenticated with check (user_id = auth.uid() and public.workspace_role(workspace_id) in ('owner','editor'));
create policy settings_update on public.settings for update to authenticated using (user_id = auth.uid() and public.workspace_role(workspace_id) in ('owner','editor')) with check (user_id = auth.uid() and public.workspace_role(workspace_id) in ('owner','editor'));
create policy settings_delete on public.settings for delete to authenticated using (user_id = auth.uid() and public.workspace_role(workspace_id) in ('owner','editor'));
create policy sync_queue_select on public.sync_queue for select to authenticated using (public.is_workspace_member(workspace_id));
create policy sync_queue_insert on public.sync_queue for insert to authenticated with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy sync_queue_update on public.sync_queue for update to authenticated using (public.workspace_role(workspace_id) in ('owner','editor')) with check (public.workspace_role(workspace_id) in ('owner','editor'));
create policy sync_queue_delete on public.sync_queue for delete to authenticated using (public.workspace_role(workspace_id) in ('owner','editor'));
